### ISSUE TITLE
Ambiguous name

### ISSUE THREAD

**Issue by mortenscheel** [milwad-dev/laravel-attributes#16]
I justed wanted to mention that the word attribute is pretty easy to misunderstand.
- Eloquent models already have attributes.
- They can also have [PHP Attributes](https://www.php.net/manual/en/language.attributes.overview.php)

I think adding another type of attributes, that are actually related models, is bound to cause a lot of confusion.

**Comment by milwad-dev** [comment]
Have you found any bugs when you are working with them?
