### ISSUE TITLE
attachAttributes store attributable and timestamps values as "NULL"

### ISSUE THREAD

**Issue by Guillermo-Blackspot** [milwad-dev/laravel-attributes#19]
You are using the "**insert**" method in such a way that **you must add "attributable_id", "attributable", "created_at", "updated_at" values** and any other value that Laravel generates automatically with eloquent 

![image](https://github.com/milwad-dev/laravel-attributes/assets/63753595/a37df528-d9df-4b9a-ad0e-7bfeea55eebc)

![image](https://github.com/milwad-dev/laravel-attributes/assets/63753595/a2de00ed-dbcc-4614-81c9-a0ceef238040)

**Comment by milwad-dev** [comment]
Which version you are using?
https://github.com/milwad-dev/laravel-attributes/blob/1.x/src/Traits/Attributable.php#L50
