### ISSUE TITLE
The "Attributes" relationship causes problems with the internal property "$attributes" of the eloquent model

### ISSUE THREAD

**Issue by Guillermo-Blackspot** [milwad-dev/laravel-attributes#20]
![image](https://github.com/milwad-dev/laravel-attributes/assets/63753595/376a3e57-3d71-4fc7-9420-a4edf65ef1e9)

The package looked good, I hope you can correct or change the names

**Comment by milwad-dev** [comment]
https://github.com/milwad-dev/laravel-attributes/blob/1.x/src/Traits/Attributable.php#L19

**Comment by kminek** [comment]
@milwad-dev hi! i just noticed this issue reported as i stumbled upon it myself - this was fixed somehow?
